version: "2"
services:
    mysql:
        image: mysql:5.6.35
        restart: always
        ports:
        - "2306:3306"
        environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=onlinejudge
    redis:
        image: redis:3.0.7
        restart: always
        ports:
        - "5379:6379"
