version: "2"
services:
    mysql:
        image: mysql:5.6.35
        restart: always
        ports:
        - "2306:3306"
        environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
        - /data/mysql:/var/lib/mysql:rw
    redis:
        image: redis:3.0.7
        restart: always
        ports:
        - "5379:6379"
        volumes:
        - /data/redis:/data:rw
    mongo:
        image: mongo:3.2.4
        restart: always
        ports:
        - "17017:27017"
        volumes:
        - /data/mongo:/data/db:rw
