Database:
  name: onlinejudge
  host: seaof-153-125-239-172.jp-tokyo-26.arukascloud.io
  port: 31857
  dialect: mysql
  username: admin
  password: fwg7aq3y2tb
  logging: !!bool true

Cache:
  host: seaof-153-125-239-173.jp-tokyo-26.arukascloud.io
  port: 31663
  auth: n91fhtn908w69f8
  db: 0
  prefix: 'onlinejudge-cache:'

Queue:
  host: seaof-153-125-239-173.jp-tokyo-26.arukascloud.io
  port: 31663
  auth: n91fhtn908w69f8
  db: 1
  prefix: 'onlinejudge-queue:'

Env: development
Port: 8000