Database:
  name: onlinejudge
  host: cloud.ruiming.me
  port: 6612
  dialect: mysql
  username: scnuoj
  password: ntsuv2o7x8naq7
  logging: !!bool true

Cache:
  host: cloud.ruiming.me
  port: 12758
  auth: bxm7GVHcoXw9ko43V1UzBfOQjH3jh83s
  db: 0

Queue:
  host: cloud.ruiming.me
  port: 12758
  auth: bxm7GVHcoXw9ko43V1UzBfOQjH3jh83s
  db: 1

Jwt:
  secret: NQUZatQ7GM8fzv0ltlQboS3gedz0HlCG
  algorithm: RS256
  exp: 5184000000

Env: development
Port: 8000
