Database:
  name: onlinejudge
  host: seaof-153-125-239-172.jp-tokyo-26.arukascloud.io
  port: 31857
  dialect: mysql
  username: admin
  password: fwg7aq3y2tb
  logging: !!bool true

Env: production
Port: 8000