Database:
  name: ENV:DB_NAME
  host: ENV:DB_HOST
  port: ENV:DB_PORT
  dialect: mysql
  username: ENV:DB_USERNAME

Cache:
  host: ENV:RE_HOST
  port: ENV:RE_PORT
  auth: ENV:RE_AUTH
  db: ENV:RE_DB
  prefix: 'onlinejudge-cache:'

Queue:
  host: ENV:RE_HOST
  port: ENV:RE_PORT
  auth: ENV:RE_AUTH
  db: ENV:RE_DB
  prefix: 'onlinejudge-queue:'

Jwt:
  secret: ENV:JWT_SECRET
  algorithm: ENV:JWT_ALGORITHM
  exp: ENV:JWT_EXP

Env: production
Port: 8000
