database:
  name: circle_test
  username: ubuntu
  options:
    host: 127.0.0.1
    port: 3306
    dialect: mysql
    timezone: Asia/Shanghai
    logging: false
    dialectOptions:
      charset: utf8
      collate: utf8_general_ci

Cache:
  host: 127.0.0.1
  port: 6379
  db: 0
  prefix: 'onlinejudge-cache:'

Queue:
  host: 127.0.0.1
  port: 6379
  db: 1
  prefix: 'onlinejudge-queue:'


Env: test
Port: 8000
